const dumy2 = [
  {
    id: 1,
    poster: "/juduldetail/96jam.png",
    judul: "96 Jam",
    shortsinopsis:
      "DINDA dan sekelompok anak SMA lainnya dari sekolah elit Mandiri Jaya berencana untuk pergi ke suatu acara festival seni di Sentul. Tak disangka, Dinda diculik bersama 5 orang teman sekelasnya; YUZA, BINTANG, TOMMY, KARIN, DARA , guru mereka – Bu SISCA dan juga cleaning service yang tak sengaja tertakangkap oleh kawanan penjahat – EMIR, dalam perjalanan menuju ke acara tersebut",
    shortsinopsisenglish:
      "DINDA and a group of other high school students from the elite Mandiri Jaya school plan to go to an arts festival in Sentul. Unexpectedly, Dinda was kidnapped along with 5 of her classmates; YUZA, BINTANG, TOMMY, KARIN, DARA, their teacher – Mrs. SISCA and also the cleaning service who was accidentally captured by the criminal colony – EMIR, on the way to the event",
    produced: "Sky Films",
    directed: "Sonu Samtani",
    director: "Wahadi Wos",
    trailer: "https://www.youtube.com/watch?v=i7mkdZp8SMs&t=1s",
    longsinopsis:
      "DINDA dan sekelompok anak SMA lainnya dari sekolah elit Mandiri Jaya berencana untuk pergi ke suatu acara festival seni di Sentul. Tak disangka, Dinda diculik bersama 5 orang teman sekelasnya; YUZA, BINTANG, TOMMY, KARIN, DARA , guru mereka – Bu SISCA dan juga cleaning service yang tak sengaja tertakangkap oleh kawanan penjahat – EMIR, dalam perjalanan menuju ke acara tersebut. Penculik yang dipimpin oleh gembong judi online, RAMOS, meminta tebusan sebesar 2 milyar per anak kepada orang tua mereka masing-masing. Ternyata Ramos bekerja sama dengan SOSOK MISTERIUS untuk menculik para anak orang kaya karena pria misterius ini mempunyai hutang judi pada Ramos. Dinda sebenarnya tak termasuk dalam list anak yang akan diculik, tapi karena Dinda menggantikan RUBI dan ikut dalam rombongan bis, Dinda pun menjadi salah satu korban. Emir ditangkap karena memergoki anak buah Ramos memantau keadaan sekolah. Bu Sisca menggantikan PAK HAMID, kepala sekolah yang tak bisa mengantar anak-anak ke acara budaya. Dinda takut dan panik. AYU – ibu Dinda bekerja di pabrik dan tak mungkin mempunyai uang sebanyak itu. Apalagi Ramos mengancam akan menjual organ tubuh Dinda dan juga Emir kalau tak ada yang bisa menebus mereka. Ramos mengirim rekaman video kepada orang tua anak-anak dan juga Pak Hamid. Tunangan Bu Sisca adalah Kapten Agung, anggota kepolisian yang langsung mengerahkan segala daya upaya untuk mencari jejak Bu Sisca dan juga anak-anak. Akankah DINDA dan anak-anak lainnya berhasil lolos dari penculikan ini??",
    longsinopsisenglish:
      "DINDA and a group of other high school students from the elite Mandiri Jaya school plan to go to an arts festival in Sentul. Unexpectedly, Dinda was kidnapped along with 5 of her classmates; YUZA, BINTANG, TOMMY, KARIN, DARA, their teacher - Mrs. SISCA and also the cleaning service who was accidentally caught by a group of criminals - EMIR, on their way to the event. The kidnappers, led by the online gambling kingpin, RAMOS, demanded a ransom of 2 billion per child from their respective parents. It turns out that Ramos collaborated with a MYSTERIOUS FIGURE to kidnap rich people's children because this mysterious man had gambling debts with Ramos. Dinda was actually not on the list of children to be kidnapped, but because Dinda replaced RUBI and joined the bus group, Dinda became one of the victims. Emir was arrested because he caught Ramos' men monitoring the situation at the school. Mrs. Sisca replaces PAK HAMID, the school principal who cannot take the children to cultural events. Dinda was afraid and panicked. AYU – Dinda's mother works in a factory and cannot possibly have that much money. Moreover, Ramos threatened to sell Dinda's and Emir's organs if no one could redeem them. Ramos sent video recordings to the children's parents and also Mr. Hamid. Mrs. Sisca's fiancé is Captain Agung, a member of the police who immediately made every effort to find traces of Mrs. Sisca and the children. Will DINDA and the other children be able to escape this kidnapping??",
    actor: [
      {
        id: 1,
        judul: "Arya Mohan",
        peran: "Bintang",
        poster: "/actor1/bintang.jpg",
        ig: "instagram.com",
      },
      {
        id: 2,
        judul: "Bastian Steel",
        peran: "Emir",
        poster: "/actor1/emir.jpg",
        ig: "instagram.com",
      },
      {
        id: 3,
        judul: "Farandika Zacht",
        peran: "Tommy",
        poster: "/actor1/tommy.jpg",
        ig: "instagram.com",
      },
      {
        id: 4,
        judul: "Donny Alamsyah",
        peran: "Hartono",
        poster: "/actor1/hartono.jpg",
        ig: "instagram.com",
      },
      {
        id: 5,
        judul: "Irzan Faiq",
        peran: "Yuza",
        poster: "/actor1/yuza.jpg",
        ig: "instagram.com",
      },
      {
        id: 6,
        judul: "Maudy Efforsina",
        peran: "Dinda",
        poster: "/actor1/dinda.jpg",
        ig: "instagram.com",
      },
      {
        id: 7,
        judul: "Gabriella Ekaputri",
        peran: "Karin",
        poster: "/actor1/karin.jpg",
        ig: "instagram.com",
      },
      {
        id: 8,
        judul: "Rifnu Wikana",
        peran: "Ramos",
        poster: "/actor1/ramos.jpg",
        ig: "instagram.com",
      },
      {
        id: 9,
        judul: "Indra Brasco",
        peran: "Hamid",
        poster: "/actor1/hamid.jpg",
        ig: "instagram.com",
      },
      {
        id: 10,
        judul: "Lea Ciarachel",
        peran: "Dara",
        poster: "/actor1/dara.jpg",
        ig: "instagram.com",
      },
    ],
  },
  {
    id: 2,
    poster: "/juduldetail/scandal.png",
    judul: "SCANDAL 2",
    shortsinopsis: "Ada seorang gadis yang selalu memandangi tempat itu dari kejauhan. Dati matanya tampak seolah berkata kalau dia ingin sekali menjejakkan kaki ke dalam tempat yang sepertinya tidak bisa dia masuki itu.",
    shortsinopsisenglish: "There was a girl who always looked at that place from a distance. Her eyes looked as if she was saying that she really wanted to set foot into a place she couldnt seem to get into.",
    produced: "Sky Films",
    directed: "Razka Robby Ertanto",
    director: "Mawan Kelana",
    trailer: "hhttps://www.youtube.com/watch?v=t4hoI9hkKtY&t=1s",
    longsinopsis:
      "Ada seorang gadis yang selalu memandangi tempat itu dari kejauhan. Dati matanya tampak seolah berkata kalau dia ingin sekali menjejakkan kaki ke dalam tempat yang sepertinya tidak bisa dia masuki itu. Dia Luna (24), gadis cantik, cerdas, selalu punya positif vibes, namun kurang beruntung. Sejak kecil dia hidup bersama Ismaya, lelaki yang berbaik hati mengasuhnya. Setelah lulus SMA, Luna bekerja di agen pariwisata milik Ismaya dan menjadi tour guide. Tapi Luna punya mimpi untuk jadi dancer, seperti ibunya dulu.",
    longsinopsisenglish:
      "There was a girl who always looked at that place from a distance. Her eyes looked as if she was saying that she really wanted to set foot into a place she couldnt seem to get into. She is Luna (24), a beautiful, intelligent girl, always has positive vibes, but is less fortunate. Since childhood, she has lived with Ismaya, a man who has been kind enough to take care of her. After graduating from high school, Luna worked at Ismayas tourism agency and became a tour guide. But Luna has a dream to become a dancer, like her mother used to be.",
    actor: [
      {
        id: 1,
        judul: "Cinta Laura",
        peran: "Luna",
        poster: "/actor2/luna.png",
        ig: "instagram.com",
      },
      {
        id: 2,
        judul: "Ibnu Jamil",
        peran: "Prince",
        poster: "/actor2/prince.png",
        ig: "instagram.com",
      },
      {
        id: 3,
        judul: "Bizael Tanasale",
        peran: "Yuda",
        poster: "/actor2/yuda.png",
        ig: "instagram.com",
      },
      {
        id: 4,
        judul: "Sheila Marsia",
        peran: "Safia",
        poster: "/actor2/safia.png",
        ig: "instagram.com",
      },
      {
        id: 5,
        judul: "Karenina",
        peran: "Netra",
        poster: "/actor2/netra.png",
        ig: "instagram.com",
      },
      {
        id: 6,
        judul: "Hans De Kraker",
        peran: "Oliver",
        poster: "/actor2/oliver.png",
        ig: "instagram.com",
      },
    ],
  },
  {
    id: 3,
    poster: "/juduldetail/canyou.png",
    judul: "Can You Hear Me",
    shortsinopsis: "Ada seorang gadis yang selalu memandangi tempat itu dari kejauhan. Dati matanya tampak seolah berkata kalau dia ingin sekali menjejakkan kaki ke dalam tempat yang sepertinya tidak bisa dia masuki itu.",
    shortsinopsisenglish: "There was a girl who always looked at that place from a distance. Her eyes looked as if she was saying that she really wanted to set foot into a place she couldnt seem to get into.",
    produced: "Sky Films",
    directed: "Hestu Saputra",
    director: "Asep Kalila",
    trailer: "https://www.youtube.com/watch?v=-nbsK_AF-ws",
    longsinopsis:
      "Ada seorang gadis yang selalu memandangi tempat itu dari kejauhan. Dati matanya tampak seolah berkata kalau dia ingin sekali menjejakkan kaki ke dalam tempat yang sepertinya tidak bisa dia masuki itu. Dia Luna (24), gadis cantik, cerdas, selalu punya positif vibes, namun kurang beruntung. Sejak kecil dia hidup bersama Ismaya, lelaki yang berbaik hati mengasuhnya. Setelah lulus SMA, Luna bekerja di agen pariwisata milik Ismaya dan menjadi tour guide. Tapi Luna punya mimpi untuk jadi dancer, seperti ibunya dulu.",
    longsinopsisenglish:
      "There was a girl who always looked at that place from a distance. Her eyes looked as if she was saying that she really wanted to set foot into a place she couldnt seem to get into. She is Luna (24), a beautiful, intelligent girl, always has positive vibes, but is less fortunate. Since childhood, she has lived with Ismaya, a man who has been kind enough to take care of her. After graduating from high school, Luna worked at Ismayas tourism agency and became a tour guide. But Luna has a dream to become a dancer, like her mother used to be.",
    actor: [
      {
        id: 1,
        judul: "Salshabilla",
        peran: "Mutia",
        poster: "/actor3/cast1.png",
        ig: "instagram.com",
      },
      {
        id: 2,
        judul: "Daffa Wardhana",
        peran: "Dimas",
        poster: "/actor3/cast2.jpg",
        ig: "instagram.com",
      },
      {
        id: 3,
        judul: "Gabriella",
        peran: "Sofie",
        poster: "/actor3/cast3.png",
        ig: "instagram.com",
      },
      {
        id: 4,
        judul: "Faris Nahdi",
        peran: "Farish",
        poster: "/actor3/cast4.png",
        ig: "instagram.com",
      },
      {
        id: 5,
        judul: "Lea Ciarachel",
        peran: "Syifa",
        poster: "/actor3/cast5.png",
        ig: "instagram.com",
      },
      {
        id: 6,
        judul: "Fadlan Holao",
        peran: "Akri",
        poster: "/actor3/cast6.png",
        ig: "instagram.com",
      },
      {
        id: 7,
        judul: "Fahira Mira",
        peran: "Eva",
        poster: "/actor3/cast7.png",
        ig: "instagram.com",
      },
      {
        id: 6,
        judul: "Jemsii",
        peran: "Galvin",
        poster: "/actor3/cast8.jpg",
        ig: "instagram.com",
      },
    ],
  },
];

export default dumy2;
